const msgs = [
  "Mesmo longe, meu coracao encontra o seu em cada pensamento.",
  "Voce e o abraco que falta no meu dia.",
  "A distancia so aumenta a saudade, mas tambem mostra o quanto vale a pena te esperar.",
  "Seu amor e o meu abrigo, mesmo quando nao posso te tocar.",
  "Cada obstaculo que vencemos juntos prova que nosso amor e invencivel.",
  "Rosa e a cor do nosso amor: delicado, doce e forte ao mesmo tempo.",
  "As estrelas sao as mensagens que o ceu envia dizendo que voce esta pensando em mim.",
  "Mesmo do outro lado do mundo, ainda sinto seu cheiro no travesseiro.",
  "Seu carinho atravessa quilometros e aquece minha alma.",
  "Nosso amor e tipo algodao doce: leve, colorido e impossivel de nao querer mais.",
  "Voce e meu por do sol favorito, mesmo pela webcam.",
  "Nosso amor e rosa, mas tambem e aco — bonito e resistente.",
  "As adversidades sao so capitulos da nossa linda historia.",
  "Estrelas me lembram seus olhos brilhando ao me ver.",
  "O amor mora na espera e cresce na saudade.",
  "Se nosso amor fosse uma flor, seria rosa e sempre florida.",
  "Mesmo longe, voce e meu lugar favorito no mundo.",
  "Voce e meu dia de sol num mundo cinza.",
  "Superamos o tempo e a distancia com um simples 'bom dia' cheio de amor.",
  "Entre tantas estrelas, encontrei voce: minha constelacao favorita.",
  "Nosso amor e tipo brigadeiro: doce, reconfortante e impossivel de resistir.",
  "Cada 'boa noite' que voce me da e um beijo na alma.",
  "A distancia nunca sera maior que o amor que eu sinto por voce.",
  "A cor rosa me lembra voce: suave, doce e cheia de ternura.",
  "Se as estrelas pudessem falar, contariam todas as vezes que desejei voce aqui.",
  "Amor verdadeiro nao tem medo de ponte, estrada ou fuso horario.",
  "O carinho que temos um pelo outro preenche qualquer vazio que a distancia deixa.",
  "Nossas chamadas de video tem mais amor do que muitos abracos por ai.",
  "Quando penso em desistir, lembro do seu sorriso e sigo mais forte.",
  "Seu amor me faz acreditar ate nos dias mais nublados.",
  "A rosa mais linda do jardim e o seu amor no meu coracao.",
  "Nosso amor brilha mais forte que qualquer estrela cadente.",
  "Mesmo em silencio, sua presença me acolhe.",
  "Cada dificuldade vencida e um laco mais forte entre nos.",
  "Seu carinho me envolve mesmo quando so escuto sua voz.",
  "Nosso relacionamento e uma viagem bonita entre coracoes que se amam.",
  "Se amor tivesse cor, seria rosa claro com glitter.",
  "Voce e minha saudade favorita.",
  "Em cada batida do meu coracao, mora um pedacinho seu.",
  "Se olhar pro ceu e ver uma estrela cadente, pode apostar: sou eu mandando amor.",
  "Voce e o abraco quente no frio da distancia.",
  "Superamos dias dificeis porque sabemos o valor do que temos.",
  "O mundo pode ser cinza, mas voce colore tudo de rosa.",
  "Sinto seu carinho ate nas mensagens com emojis bregas.",
  "Voce e meu cafe quentinho num dia cansativo.",
  "Nossa historia e a prova de que amor vence tudo.",
  "Mesmo longe, voce me conhece mais do que muita gente perto.",
  "Voce e meu sinal de esperanca em forma de mensagem.",
  "Quando olho pro ceu e vejo estrelas, lembro do brilho do seu olhar.",
  "Nosso amor e como rosa do deserto: floresce mesmo nas condicoes mais dificeis.",
  "Seus audios me fazem sorrir como se voce estivesse aqui do lado.",
  "A distancia e apenas um numero quando o coracao esta perto.",
  "Voce e meu pedacinho de ceu rosa.",
  "Nunca subestime o poder de um 'te amo' enviado de longe.",
  "Quando fecho os olhos, e seu rosto que aparece primeiro.",
  "Estrelas sao como lembretes de que voce esta sempre comigo.",
  "Voce e minha calma na tempestade, meu cobertor de carinho.",
  "Nosso amor e feito de pequenas coisas grandes demais pra caber na distancia.",
  "Se for pra lutar, que seja por nos.",
  "Voce e o perfume bom que fica mesmo quando a presenca vai.",
  "A cor do nosso amor e rosa com brilho de estrela.",
  "Mesmo no silencio, seu carinho fala alto.",
  "Entre mil quilometros, escolho voce todos os dias.",
  "A saudade doi, mas o amor cura.",
  "Seu amor e meu lugar seguro, mesmo a distancia.",
  "Voce e meu pedaco de ceu cor-de-rosa.",
  "A distancia nunca apaga o que o coracao grava.",
  "Se amar voce de longe e dificil, nao amar seria impossivel.",
  "Nossas conversas sao mais que palavras — sao carinho puro.",
  "A esperanca de te ver de novo me da forcas todos os dias.",
  "Voce e meu lar, mesmo em outro estado, pais ou planeta.",
  "Nosso amor cabe em emojis, risos e silencios cheios de afeto.",
  "Voce e minha flor rosa no jardim das incertezas.",
  "Nada brilha mais que o seu nome no meu celular.",
  "Superamos a distancia porque nosso amor e maior que ela.",
  "Voce e meu sol cor-de-rosa num ceu de nuvens.",
  "Amar voce e a coisa mais bonita que ja me aconteceu.",
  "Mesmo quando o mundo pesa, seu carinho me alivia.",
  "Nosso amor e constelacao: cada estrela e um momento nosso.",
  "Voce e a razao dos meus suspiros sorridentes.",
  "A distancia me ensinou a valorizar ate seus 'oi' rapidos.",
  "Nosso carinho e feito de presenca emocional, e isso ninguem mede.",
  "Seu amor faz meu coracao dancar em silencio.",
  "Estar com voce e como viver num conto de fadas moderno.",
  "Voce e o bom dia que faz meu dia bom.",
  "As adversidades so tornam nosso amor mais epico.",
  "A cor rosa e meu lembrete visual de voce.",
  "Se eu pudesse, te mandava flores rosa todo dia.",
  "Cada batida do meu coracao ecoa seu nome.",
  "Voce e meu lugar feliz em qualquer lugar do mundo.",
  "Nosso amor se escreve com sorrisos e termina com suspiros.",
  "O universo nos separou em quilometros, mas nos uniu em sintonia.",
  "Se eu pudesse tocar uma estrela por cada vez que penso em voce, teria uma galxia inteira.",
  "Sua voz tem o poder de acalmar minhas tempestades.",
  "Nosso amor e como filme bonito: da vontade de ver sempre de novo.",
  "Voce e o melhor 'final feliz' da minha historia.",
  "A cor rosa me lembra o seu jeito doce de existir.",
  "Voce e meu eterno bilhetinho fofo da vida.",
  "Se a distancia nos desafia, o amor nos une mais.",
  "Mesmo com mapas e fronteiras, meu coracao sabe onde voce esta.",
  "Voce e a saudade mais linda que ja senti.",
  "Nosso amor e como por do sol rosa: sempre vale a pena esperar.",
];
