const msgs = [
  "Mesmo longe, meu coração encontra o seu em cada pensamento.",
  "Você é o abraço que falta no meu dia.",
  "A distância só aumenta a saudade, mas também mostra o quanto vale a pena te esperar.",
  "Seu amor é o meu abrigo, mesmo quando não posso te tocar.",
  "Cada obstáculo que vencemos juntos prova que nosso amor é invencível.",
  "Rosa é a cor do nosso amor: delicado, doce e forte ao mesmo tempo.",
  "As estrelas são as mensagens que o céu envia dizendo que você está pensando em mim.",
  "Mesmo do outro lado do mundo, ainda sinto seu cheiro no travesseiro.",
  "Seu carinho atravessa quilômetros e aquece minha alma.",
  "Nosso amor é tipo algodão doce: leve, colorido e impossível de não querer mais.",
  "Você é meu pôr do sol favorito, mesmo pela webcam.",
  "Nosso amor é rosa, mas também é aço — bonito e resistente.",
  "As adversidades são só capítulos da nossa linda história.",
  "Estrelas me lembram seus olhos brilhando ao me ver.",
  "O amor mora na espera e cresce na saudade.",
  "Se nosso amor fosse uma flor, seria rosa e sempre florida.",
  "Mesmo longe, você é meu lugar favorito no mundo.",
  "Você é meu dia de sol num mundo cinza.",
  "Superamos o tempo e a distância com um simples 'bom dia' cheio de amor.",
  "Entre tantas estrelas, encontrei você: minha constelação favorita.",
  "Nosso amor é tipo brigadeiro: doce, reconfortante e impossível de resistir.",
  "Cada 'boa noite' que você me dá é um beijo na alma.",
  "A distância nunca será maior que o amor que eu sinto por você.",
  "A cor rosa me lembra você: suave, doce e cheia de ternura.",
  "Se as estrelas pudessem falar, contariam todas as vezes que desejei você aqui.",
  "Amor verdadeiro não tem medo de ponte, estrada ou fuso horário.",
  "O carinho que temos um pelo outro preenche qualquer vazio que a distância deixa.",
  "Nossas chamadas de vídeo têm mais amor do que muitos abraços por aí.",
  "Quando penso em desistir, lembro do seu sorriso e sigo mais forte.",
  "Seu amor me faz acreditar até nos dias mais nublados.",
  "A rosa mais linda do jardim é o seu amor no meu coração.",
  "Nosso amor brilha mais forte que qualquer estrela cadente.",
  "Mesmo em silêncio, sua presença me acolhe.",
  "Cada dificuldade vencida é um laço mais forte entre nós.",
  "Seu carinho me envolve mesmo quando só escuto sua voz.",
  "Nosso relacionamento é uma viagem bonita entre corações que se amam.",
  "Se amor tivesse cor, seria rosa claro com glitter.",
  "Você é minha saudade favorita.",
  "Em cada batida do meu coração, mora um pedacinho seu.",
  "Se olhar pro céu e ver uma estrela cadente, pode apostar: sou eu mandando amor.",
  "Você é o abraço quente no frio da distância.",
  "Superamos dias difíceis porque sabemos o valor do que temos.",
  "O mundo pode ser cinza, mas você colore tudo de rosa.",
  "Sinto seu carinho até nas mensagens com emojis bregas.",
  "Você é meu café quentinho num dia cansativo.",
  "Nossa história é a prova de que amor vence tudo.",
  "Mesmo longe, você me conhece mais do que muita gente perto.",
  "Você é meu sinal de esperança em forma de mensagem.",
  "Quando olho pro céu e vejo estrelas, lembro do brilho do seu olhar.",
  "Nosso amor é como rosa do deserto: floresce mesmo nas condições mais difíceis.",
  "Seus áudios me fazem sorrir como se você estivesse aqui do lado.",
  "A distância é apenas um número quando o coração está perto.",
  "Você é meu pedacinho de céu rosa.",
  "Nunca subestime o poder de um 'te amo' enviado de longe.",
  "Quando fecho os olhos, é seu rosto que aparece primeiro.",
  "Estrelas são como lembretes de que você está sempre comigo.",
  "Você é minha calma na tempestade, meu cobertor de carinho.",
  "Nosso amor é feito de pequenas coisas grandes demais pra caber na distância.",
  "Se for pra lutar, que seja por nós.",
  "Você é o perfume bom que fica mesmo quando a presença vai.",
  "A cor do nosso amor é rosa com brilho de estrela.",
  "Mesmo no silêncio, seu carinho fala alto.",
  "Entre mil quilômetros, escolho você todos os dias.",
  "A saudade dói, mas o amor cura.",
  "Seu amor é meu lugar seguro, mesmo à distância.",
  "Você é meu pedaço de céu cor-de-rosa.",
  "A distância nunca apaga o que o coração grava.",
  "Se amar você de longe é difícil, não amar seria impossível.",
  "Nossas conversas são mais que palavras — são carinho puro.",
  "A esperança de te ver de novo me dá forças todos os dias.",
  "Você é meu lar, mesmo em outro estado, país ou planeta.",
  "Nosso amor cabe em emojis, risos e silêncios cheios de afeto.",
  "Você é minha flor rosa no jardim das incertezas.",
  "Nada brilha mais que o seu nome no meu celular.",
  "Superamos a distância porque nosso amor é maior que ela.",
  "Você é meu sol cor-de-rosa num céu de nuvens.",
  "Amar você é a coisa mais bonita que já me aconteceu.",
  "Mesmo quando o mundo pesa, seu carinho me alivia.",
  "Nosso amor é constelação: cada estrela é um momento nosso.",
  "Você é a razão dos meus suspiros sorridentes.",
  "A distância me ensinou a valorizar até seus 'oi' rápidos.",
  "Nosso carinho é feito de presença emocional, e isso ninguém mede.",
  "Seu amor faz meu coração dançar em silêncio.",
  "Estar com você é como viver num conto de fadas moderno.",
  "Você é o bom dia que faz meu dia bom.",
  "As adversidades só tornam nosso amor mais épico.",
  "A cor rosa é meu lembrete visual de você.",
  "Se eu pudesse, te mandava flores rosa todo dia.",
  "Cada batida do meu coração ecoa seu nome.",
  "Você é meu lugar feliz em qualquer lugar do mundo.",
  "Nosso amor se escreve com sorrisos e termina com suspiros.",
  "O universo nos separou em quilômetros, mas nos uniu em sintonia.",
  "Se eu pudesse tocar uma estrela por cada vez que penso em você, teria uma galáxia inteira.",
  "Sua voz tem o poder de acalmar minhas tempestades.",
  "Nosso amor é como filme bonito: dá vontade de ver sempre de novo.",
  "Você é o melhor 'final feliz' da minha história.",
  "A cor rosa me lembra o seu jeito doce de existir.",
  "Você é meu eterno bilhetinho fofo da vida.",
  "Se a distância nos desafia, o amor nos une mais.",
  "Mesmo com mapas e fronteiras, meu coração sabe onde você está.",
  "Você é a saudade mais linda que já senti.",
  "Nosso amor é como pôr do sol rosa: sempre vale a pena esperar.",
];
